pipeline {
    agent any

    environment {
        IMAGE_NAME = 'nabeel1279/react-app'
        TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/nabeel329/Todo_APP_updated.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('todo_app') {   // 👈 go inside todo_app folder
                    sh 'docker build -t $IMAGE_NAME:$TAG .'
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                dir('todo_app') {   // 👈 also push from inside todo_app
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                            docker push $IMAGE_NAME:$TAG
                        '''
                    }
                }
            }
        }
    }
}
