pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-creds'
        IMAGE_NAME = 'nabeel1279/react-app'
        TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/nabeel329/Todo_APP_updated.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('todo_app') {   // 👈 go inside todo_app folder
                    script {
                        sh 'docker build -t $IMAGE_NAME:$TAG .'
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                dir('todo_app') {   // 👈 also push from inside todo_app
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS) {
                            sh 'docker push $IMAGE_NAME:$TAG'
                        }
                    }
                }
            }
        }
    }
}
